#!/bin/sh

FILE="${1:-access.log}"
BASEDIR="${BASEDIR:-$(dirname $0)}"

usage(){
  cat >&2 << EOF
Can't find "${FILE}"

Usage: $(basename $0) LOGTOPROCESS [COMMAND]
EOF
  exit 1
}

[ -r "${FILE}" ] || usage
"${BASEDIR}/process_apache_log" "${FILE}" "$2" | "${BASEDIR}/filldb" "${BASEDIR}/json_median_size"
