#!/bin/sh

usage() {
  cat >&2 << EOF
Usage: $(basename $0) access.log [COMMAND]

  COMMAND is a command used to browse log, like "tail -f"
          Default: cat
EOF
  exit 1
}

[ -z "$1" ] && usage
COMMAND="${2:-cat}"

if awk -Wversion 2>&1 | grep -q mawk; then
  AWK_PARAM='-Winteractive'
fi

if [ "${COMMAND}" != 'cat' ] && awk -Wversion 2>&1 | grep -q 'GNU Awk'; then
  echo "WARNING: GNU Awk doesn't work correctly with \`tail -f\`, use mawk instead" >&2
fi

${COMMAND} $1 | awk "${AWK_PARAM}" '($10 != "-"){ print $9,$10 }'
